name: Relase

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      
permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux (gnu)
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
  
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}

      - name: Build server
        shell: bash
        run: |     
          dirname="hookhub-server-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          mv "target/${{ matrix.target }}/release/server" "$dirname/hookhub-server"

          tar -czf "$dirname.tar.gz" "$dirname"
          echo "SERVER_ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Build client
        shell: bash
        run: |     
          dirname="hookhub-client-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          mv "target/${{ matrix.target }}/release/client" "$dirname/hookhub-client"

          tar -czf "$dirname.tar.gz" "$dirname"
          echo "CLIENT_ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Upload the binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.SERVER_ASSET }}
            ${{ env.CLIENT_ASSET }}